### ISSUE TITLE
Add have_delivered_emails expectation

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/carbon#26]
`expect(Carbon).to have_delivered_emails`

Just tests that it delivered *any* emails

**Comment by matthewmcgarvey** [comment]
Other options for expectations

```crystal
# expectations on emails
AccountConfirmEmail.should have_been_delivered
```

There could be optional arguments to assert on who it was emailed to?

**Comment by matthewmcgarvey** [comment]
This would only work with `Carbon::DevAdapter` because it maintains a list of sent emails so it will need to raise an exception if it isn't the adapter.

**Comment by jwoertink** [comment]
Could this maybe just assert that the deliver method is called? I've never used it, but maybe the macro `finished` could be used to say the object did all it's supposed to, so let's mark it as "delivered"? Or we set a flag on https://github.com/luckyframework/carbon/blob/master/src/carbon/email.cr#L105 ? Just tossing out some ideas so that way no matter which adapter you have, it would still know. I guess we'd just have to have a way to tell all adapters that when in test, don't really send an email...

I guess you would probably not have a real adapter set in test, right? Thinking about it more.... Maybe we're just saying that "at this point in your code, an email would go out"... 🤔  ok, maybe it's fine to just be on the `DevAdapter`? lol 😂  ignore me... rambling 🤪

**Comment by matthewmcgarvey** [comment]
@jwoertink I could see Carbon being updated to maintain some sort of "memory" of emails sent for dev purposes but I really don't think anything other than the `DevAdapter` should be used in testing
