### ISSUE TITLE
File attachment

### ISSUE THREAD

**Issue by anykeyh** [luckyframework/carbon#29]
Hello,

Any way to attach files on email? I cannot find it in the documentation.

**Comment by paulcsmith** [comment]
Hi @anykeyh Right now there is not a way to attach files. I'll leave this open though in case someone wants to try tackling that

**Comment by syl-p** [comment]
Have you got any news about this issue ? We need to send some attachment to our notification mail. Have you got any alternative ?

**Comment by jwoertink** [comment]
@syl-p There hasn't been any update to this as of yet. I think we would just need to make a method that returns a JSON::Any of the content-type, filename, and a Base64 endcoded content. Then that method would be passed down to each implementation (i.e. sendgrid_adapter, etc...)

I don't really know anything about email file attachments which is why I haven't touched this. I'm open to a PR if you have a better understanding of how they'd work. :smile:

**Comment by akadusei** [comment]
Shouldn't this be closed by #88?

**Comment by jwoertink** [comment]
Yup. This is done now.
