### ISSUE TITLE
Add middleware for viewing sent emails

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/carbon#3]

**Comment by hfjallemark** [comment]
If this is about the `DevAdapter` I would propose a simpler solution (at least in the interim); just log the e-mail in the console.

I did this locally to see the e-mail contents:

```
def deliver_now(email : Carbon::Email)
  puts email.text_body
 @@delivered_emails << email
end
```

**Comment by paulcsmith** [comment]
I like that idea as a nice interim solution! I'm thinking DevAdapter can accept an argument so that it doesn't print in test:

```crystal
Carbon::DevAdapter.new(print_emails: Lucky::Env.development?)
```

I'll create an issue for this

**Comment by matthewmcgarvey** [comment]
Looking at this issue, I assume by "middleware" you mean adding a way to provide http endpoints to view sent emails.

Since we recently created [pulsar](https://github.com/luckyframework/pulsar) I'm thinking that we add events to the carbon library and then a new shard could be made with a dependency on carbon and lucky (because carbon does not depend on lucky right now and it probably shouldn't) and listens to those events and provides some nice pages.

**Comment by matthewmcgarvey** [comment]
A general purpose admin/development tool is being made with a plan to integrate with carbon. In order to do that, we need to add pulsar and events. "middleware" is not needed at this point.

Replaced by https://github.com/luckyframework/carbon/issues/43
